Repository framgia/sph_unity-dkk, pull requests merged in 2022-04, with the labels that each got.

#29 [Task] Add basic UI elements in-game
  .gitignore
  Assets/Prefabs/Canvas.prefab
  Assets/Prefabs/Canvas.prefab.meta
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/UI.cs
  Assets/Scripts/UI.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  UserSettings/EditorUserSettings.asset
Labels: enhancement, Approved by roman, Approved by drei

#38 [BUG] Barrier Height Adjustment
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
  UserSettings/EditorUserSettings.asset
Labels: bug, Approved by roman, Approved by drei

#43 [FIX] fixed mario sprite order
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
Labels: bug, Approved by roman
